function F = regWaveF(t,x,wave,wave2F)
   % --- Regular wave ------------------
   % not updated with [x(1:2,:)]
   % 2Do: attach wave2F to bodies; 
   %      add updation of position
   % F = wave2F.Xamp.*(wave.Za*cos(-wave.omega*t +...
   %                  [wave.kX,wave.kY]*[0;0] +...
   %                   wave.phase + wave2F.phase));
   F = wave2F.Xamp.*(wave.Za*sin(wave.omega*t -...
                    [wave.kX,wave.kY]*[0;0] +...
                     wave.phase + wave2F.phase));
   % -----------------------------------
end